### ISSUE TITLE
Is this project still maintianed?

### ISSUE THREAD

**Issue by ghost** [Alloyed/lua-lsp#13]
Is this project still maintianed?

**Comment by Alloyed** [comment]
Well, I'm still around, I guess? I've recently taken a new job that has eaten up the time that I would otherwise spend here, but if there are any specific issues or PRs I'd be happy to take a look, and if you'd like to fork from here I'm okay with that too. I have a few local changes that I haven't been pushing up for probably not so good reasons; I'll see what I can do get those in.
