### ISSUE TITLE
Starting lua-lsp fails

### ISSUE THREAD

**Issue by dschuessler** [Alloyed/lua-lsp#15]
I installed lua-lsp with `luarocks install --server=http://luarocks.org/dev lua-lsp`. Starting `lua-lsp` in the command line results in the following error:

```
/usr/local/bin/lua5.3: /usr/local/share/lua/5.3/lua-lsp/rpc.lua:2: module 'dkjson' not found:Failed loading module dkjson in LuaRocks rock dkjson 2.5-2
	no field package.preload['dkjson']
	no file '/Users/dschuessler/.luarocks/share/lua/5.3/dkjson.lua'
	no file '/Users/dschuessler/.luarocks/share/lua/5.3/dkjson/init.lua'
	no file '/usr/local/share/lua/5.3/dkjson.lua'
	no file '/usr/local/share/lua/5.3/dkjson/init.lua'
	no file '/usr/local/lib/lua/5.3/dkjson.lua'
	no file '/usr/local/lib/lua/5.3/dkjson/init.lua'
	no file './dkjson.lua'
	no file './dkjson/init.lua'
	no file '/Users/dschuessler/.luarocks/lib/lua/5.3/dkjson.so'
	no file '/usr/local/lib/lua/5.3/dkjson.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './dkjson.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.3/lua-lsp/rpc.lua:2: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.3/lua-lsp/loop.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/lib/luarocks/rocks-5.3/lua-lsp/scm-2/bin/lua-lsp:2: in main chunk
	[C]: in ?
```

Thank you for having a look. Let me know if there is any further troubleshooting I can help with.

macOS 10.13.4
Lua 5.3

**Comment by AitorATuin** [comment]
`luarocks list dkjson` should tell you if dkjson is installed at all and where.

**Comment by dschuessler** [comment]
```
Installed rocks:
----------------

dkjson
   2.5-2 (installed) - /usr/local/lib/luarocks/rocks-5.3
```

Am I supposed to do something with this information?

**Comment by Alloyed** [comment]
Hey sorry for being nonexistent for several months

Aitor is right in that luarocks should've installed a copy of dkjson.lua somewhere, but that lua-lsp is having trouble finding it. The search path for modules is supposed to be managed by luarocks, so I can only guess at what's going wrong. Since lua-lsp itself is in /usr/local/share/lua/5.3, my guess is that dkjson is _supposed_ to be there too, but something's up.

you can try finding the install using `locate dkjson.lua` but it might be easier to bulldoze your existing install and start over. if you type `luarocks`, at the bottom it will tell you what trees are currently supported: you can purge them using `luarocks purge --tree=$(the_tree)` and then try reinstalling from there.

**Comment by dschuessler** [comment]
Purging the tree and starting over did it. Thanks for the help!
