### ISSUE TITLE
Add lua-fmt as a formatter

### ISSUE THREAD

**Issue by ThaisRobba** [Alloyed/lua-lsp#21]
[lua-fmt](https://github.com/trixnz/lua-fmt) is, at the moment, the most powerful and consistent formatter for Lua.

It works with multiple Lua versions, is well tested and is the only one so far that handles things like lines that are too long due to function calls - breaking arguments into multiple lines.

It has places that could be improved but the creator and maintainer, Trinx, is really open to contributions and feedback.

**Comment by pablomayobre** [comment]
lua-fmt is a TypeScript tool, which requires Node.js to work... It's way more complicated to include it as part of this project, since this is mostly a pure Lua project, you would need to run `io.popen` and all that stuff in order to interact with it, and checking if the program is there would be more complicated (currently lua-lsp uses luarocks to get the paths to other projects like luacheck, lcf and such)

**Comment by vadi2** [comment]
Indeed. What _is_ a nice Lua code formatter, pure-Lua, is https://github.com/martin-eden/lua_code_formatter.

**Comment by pablomayobre** [comment]
Yeah that's LCF, And it's already supported in lua-lsp since bd7bc626408b1abbd8268a1ef272245be341c31b

**Comment by Alloyed** [comment]
rolling into #2 to lower open issues, but I don't think it's necessarily a bad idea: It is more work than just supporting a lua API but we already do that work to support luacheck, it's just a matter of having a stable CLI interface
