### ISSUE TITLE
[Question] How to resolve specific require paths?

### ISSUE THREAD

**Issue by slmjkdbtl** [Alloyed/lua-lsp#22]
I'm using a library that use a specific require path like love2d, and it raise error when trying to jump to definitions from another file. How to configure to work with this? 

I'm using neovim and the LanguageClient-neovim plugin, and setting `g:LanguageClient_rootMarkers = ['main.lua',]` doesn't work.

**Comment by Alloyed** [comment]
SO: super late response, and my assumption is that you probably aren't using lua-lsp anymore, but on the off-chance you/anybody else who comes across this bug can provide more info that'd be very helpful to help me prioritise future work:

cross-file jump to definition right now works in a very limited way: if you have a local module that is defined using the 'require' command, we can follow that module up the chain to find methods on it. Globals afaict do not work: with a bit of elbow grease I may be able to fix them up IF the file where you defined the global is currently open (we don't support full project scanning yet, either).

To follow require paths, we use the field packagePath in your luaCompleterc, which defaults to "./?.lua". This _should_ work for most uses of love, but if the problem is really in the finding of different modules, that's also good to know.

**Comment by Alloyed** [comment]
closed due to age
